github.com:
    users:
        matheus1-ex:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: matheus1-ex
