# This is a basic workflow to help you get started with Actions

name: projBioSite

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    # Rodar por comando
    runs-on: ubuntu-latest
    
    steps:
      # Checar o código
      - name: Checkout no código
        uses: actions/checkout@v4

      # Validar a sintaxe do Dockerfile (Hadolint)
      - name: Validar a sintaxe do Dockerfile
        uses:
          with:
            dockerfile: Dockerfile

      - name: Testar o build da imagem do Docker
        run: docker build -t biosite_orizon:test .
        
      # Configurar o Node.js
      - name: Configurar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      # Instalar Dependências para evitar erros
      - name: Instalar dependências
        run: npm ci

      # Validação do HTML
      - name: Validar html
        run: npm run lint:html

      
      # Validação do CSS
      - name: Validar Css
        run: npm run lint:css