# This is a basic workflow to help you get started with Actions

name: projBioSite

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    # Rodar por comando
    runs-on: ubuntu-latest

    steps:
      # Baixar o repositório
      - name: Baixar o repositório
        uses: actions/checkout@v7

      # Verificar o HTML (HtmlHint)
      - name: Verificar HTML
        run: |
          npx htmlhint "**/*.html"

      # Agora é verificar o CSS (Stylelint)
      - name: Verificar CSS
        run: |
          npx stylelint "**/*.css"
